name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull the Docker image
      run: docker pull deepaiorg/gpt2
    - name: Run image
      run: echo '{"text":"I am very happy because this model is great!"}' | docker run -e MODE=test_inputs_dict_json --rm -i deepaiorg/gpt2
