name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull the Docker image
      run: docker pull deepaiorg/gpt2
    - name: Run image
      run: docker run --rm -it -t -v `pwd`:/shared -e MODE=command_line deepaiorg/gpt2 --text /shared/input.txt
